### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by Vaxeral** [unicurses/unicurses#15]
I ran pip3 install uni-curses but when trying to import the module as unicurses i get a ModuleNotFound error.

**Comment by GiorgosXou** [comment]
Indeed i need to re-check the setup.py cause i've also had the same issue with python-3.9 *(although for some reason not with 3.8)* on my ubuntu laptop

**Comment by GiorgosXou** [comment]
>I think that the Pypi version is still using the Sourceforge version 1.2 of unicurses...

That's only true if you do `pip3 install unicurses` and not `pip3 install uni-curses` make sure it has `-` between.


>...requires that the user also go get a "pdcurses.dll" from the original PDCurses Sourceforge site and copy that DLL into the same directory where the unicurses.py source code is installed by pip3, but the only binary DL provided at the Sourceforge site is for the very old python V3.4. To get a "pdcurses.dll" compatible with more current python versions you have to rebuild pdcurses from source DL'ed from the pdcurses Sourceforge site.

There are both [32bit](https://github.com/unicurses/unicurses/tree/master/unicurses/32%20bit%20binaries) and [64bit](https://github.com/unicurses/unicurses/tree/master/unicurses/64%20bit%20binaries) binaries of the latest 3.9 version of PDCurses in this repo, you don't need to compile them by yourself unless you want so.

>I have a question of my own. When you say "download the repo", do you mean git clone or just DL a zip of the repository here?

Yeah Just the zip file of this repo. 


>Some specific installation instructions would be helpful 

True, i agree.


>I don't think that pip3 can be used to install this github version of unicurses (though I would love to be proved wrong about that).

If you haven't tried allready to `pip3 install uni-curses` *(make sure it has `-`)* try downloading the repo zip , extract it anywhere, then `cd` into the folder and run `python setup.py install`. if this wont work let me know 


### in my case everything works fine though...
![image](https://user-images.githubusercontent.com/11987271/136710483-51142bb8-8144-494c-bf98-5fdf557ea106.png)

**Comment by pjfarleyiii** [comment]
Thanks for the detailed instructions.  I was able to install uni-curses in a python virtualenv via pip3 and successfully run the test_panels_advanced.py script which always crashed for me previously.

A suggestion: Is it possible for the demos directory in the repo to be installed along with uni-curses?  I looked around in the site-packages directory of my virtualenv after installing uni-curses and it is not there.  This is a complaint I have about many python packages  -- they have wonderful and helpful demo directories that aren't installed along with the code, so you have to go download or clone the repository to get the demo directory.  This is annoying, though I do understand the philosophy of "don't install anything but the executables" for environments that aren't on a developer's machine.

Anyway, many thanks for the updates!  Now I can really explore this package to see if it will do what I need.

Peter
