### ISSUE TITLE
Fails to import pdcurses on windows 64 bit

### ISSUE THREAD

**Issue by fuzzything44** [unicurses/unicurses#2]
I'm guessing that the pdcurses dll in /unicurses/pdc34dll is somehow not compatible with 64 bit Python 3.6 or Windows 10. 

I'm getting a failure to import it (OSError: [WinError 193] %1 is not a valid Win32 application) when attempting to create a `ctypes CDLL` object (line 71 of `__init__.py` of unicurses, line 348 of `__init__.py` of ctypes.)

**Comment by Chiel92** [comment]
I would guess that its a 32 bit dll, yeah. If you can get hold of 64 bit versions we could probably write some logic that loads the right dll based on whether we are a 64 or 32 bit process.

**Comment by fuzzything44** [comment]
Yeah, after more testing I've concluded that it's the 32 bit dll as it works with 32 bit Python 3.4.
