### ISSUE TITLE
Expecting pdcurses problem

### ISSUE THREAD

**Issue by eiffelcn** [unicurses/unicurses#24]
In empty PY3 anaconda environment on Window11, after pip install uni-curses, run an empty test.py with only 'from unicurses import *'.
It will show a notice 'Expecting pdcurses at: C:\<venv_dir>\Lib\site-packages\unicurses/64 bit binaries/pdcdllu/pdcurses.dll' at 'from unicurses import *'. But it seems that the curses features are available and the program won't panic for the notice.
I have try on py3.11 py3.10 py3.6, they will get the same problem.
How to resolve the noice notice at import unicurses?

**Comment by GiorgosXou** [comment]
I just forgot to remove it, it doesn't really need to be there actually, I will do so in the next days
https://github.com/unicurses/unicurses/blob/master/unicurses/__init__.py#L103

**Comment by GiorgosXou** [comment]
I meant [Line 106](https://github.com/unicurses/unicurses/blob/8578634ad19ac70547bfb7c19b5cbb29d4af9063/unicurses/__init__.py#L106)
