### ISSUE TITLE
Breaks with Python 3.12  due to removal of distutils 

### ISSUE THREAD

**Issue by Dark-Sider** [unicurses/unicurses#34]
I found that uni-curses breaks with Python 3.12 due to distutils being removed (https://docs.python.org/3.10/library/distutils.html):

```
  File "C:\Python312\Lib\site-packages\unicurses\__init__.py", line 23, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```
I installed Python via their official site and installed unicurses vie `pip install uni-curses`

I was able to use unicurses after removing line 23 from `__init__.py` by putting a `#` infront of the line.

My code is working again, but I don't know if this a valid fix for everyone

**Comment by GiorgosXou** [comment]
Oh... Thanks for the catch! It should be removed, this is a valid fix. ([It was there since version 1.1](https://github.com/unicurses/unicurses/blob/7c3b0f3f9ea91a968fe7b51ffeb8756f2c68f872/changelog.md?plain=1#L12))
