### ISSUE TITLE
mvdeleteln does not work (quick workaround)

### ISSUE THREAD

**Issue by ttoommxx** [unicurses/unicurses#36]
As the title says, mvdeleteln does not work and gives the following message
```
AttributeError: /lib64/libncursesw.so.6: undefined symbol: mvwdeleteln
```
I checked on the man page and such method simply does not exists, so how about substituting it with
```
def mvdeleteln( y, x ):
    old_y, old_x = unicurses.getyx( stdscr )
    unicurses.move( y, x )
    unicurses.deleteln()
    unicurses.move( old_y, old_x )
```

**Comment by GiorgosXou** [comment]
> I checked on the man page and such method simply does not exists
True, but [PDCurses has it](https://github.com/search?q=repo%3Awmcbrine%2FPDCurses%20mvdeleteln&type=code).

> so how about substituting it with ...

Close enough! you should change `mvwdeleteln` instead of `mvdeleteln`. Something like this could work:
```python
def mvwdeleteln(scr_id, y, x):
    if NCURSES:
        old_y, old_x = getyx( stdscr )
        lib1.wmove(scr_id, y, x)
        lib1.wdeleteln(scr_id)
        lib1.wmove(scr_id, old_y, old_x)
    else:
        return lib1.mvwdeleteln(scr_id, y, x)
```
*(^^^ not tested. Going to sleep right now, it's too late here 😴)*

**Comment by ttoommxx** [comment]
Great, will try to commit tonight :)
