### ISSUE TITLE
'c_void_p' object has no attribute 'getch'

### ISSUE THREAD

**Issue by retr00h** [unicurses/unicurses#40]
Hello. I am trying to get started with unicurses but I'm facing the following error when running the few lines of code I've written.
The full traceback is:

```
Traceback (most recent call last):
  File "c:\Users\fabio\OneDrive\test.py", line 6, in <module>
    wrapper(main)
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\site-packages\unicurses\__init__.py", line 2911, in wrapper
    raise error
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python312\Lib\site-packages\unicurses\__init__.py", line 2909, in wrapper
    return function(stdscr, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fabio\OneDrive\test.py", line 4, in main
    stdscr.getch()
    ^^^^^^^^^^^^
AttributeError: 'c_void_p' object has no attribute 'getch'
```
While the code the generates this error is the following:
```
from unicurses import wrapper

def main(stdscr):
    stdscr.getch()

wrapper(main)
```

I am using Python 3.12 if that may help

**Comment by ttoommxx** [comment]
You should not use `stdscr` as an object, it is not, it's literally just a pointer. This library works differently from the standard curses Python library.

```
import unicurses
from unicurses import wrapper

def main(stdscr):
    unicurses.getch()

wrapper(main)
```
this fixes your issue.

The reason for having `stdscr` is that some of functions within the library requires specifying the window to use for printing, but it's not an object!

**Comment by GiorgosXou** [comment]
Additionally, take a look at the [demos](https://github.com/unicurses/unicurses/tree/master/demos) or at the [getting started section](https://github.com/unicurses/unicurses?tab=readme-ov-file#getting-started) for more informations.
