### ISSUE TITLE
getkey and wgetkey

### ISSUE THREAD

**Issue by derDere** [unicurses/unicurses#5]
I'm unable to get the arrow keys and also use the escape key because wgetkey is giving me the same result as wgetch.
If I'm not misstaken wgetkey should give the same result as getkey.

Example:
using getkey, pressing ArrowUp, receiving "KEY_UP"
using wgetkey, pressing ArrowUp, receiving "\x1b", next times receiving "[" and "A"

**Comment by Chiel92** [comment]
I'd say you are right. If you find a culprit feel free to open a PR.

**Comment by ttoommxx** [comment]
This is fixed now, can you close this issue?
